# -*- coding: utf-8 -*-
"""assigmentFeb27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t5qe_0D1FW3QFt-HTVw9PEx8hxdJX8Lj
"""

count, fruit, price = (2, 'apple', 3.5)
type(count)

mylist = ['NEWYORK', 'LONDRA', 'TOKYO', 'NAPOLI']
mylist.pop(2) 
print(mylist)

car_dict = {1:{'Toyota':{'Corola':{'Blue', '2010', '180,000 km', '$2500'},
                         'Yaris':{'Silver', '2013', '120,000 km', '$3000'}}},
            2:{'HONDA':{'CIVIC':{'Gray', '2015', '10,000 km', '$2800'}}}
            }
                        
print(car_dict)
print(car_dict[1])
print(car_dict[2])
print(car_dict[1]['Toyota']['Yaris'])

college_years = ['Freshman', 'Sophomore', 'Junior', 'Senior']
print(list(enumerate(college_years, 2019)))

fruits = ['Apples', 'Oranges', 'Bananas']
quantities = [5, 3, 4]
prices = [1.50, 2.25, 0.89]
i = 0
output = []
for fruit in fruits:
    temp_qty = quantities[i]
    temp_price = prices[i]
    output.append((fruit, temp_qty, temp_price))
    i += 1
print(output)

fruits = ['Apples', 'Oranges', 'Bananas']
quantities = [5, 3, 4]
prices = [1.50, 2.25, 0.89]
groceries = zip(fruits, quantities, prices)
print(list(groceries))

state = True
age = ''
while not age.isnumeric():
    age = input('Enter Your age --> ')

print(age)

sentence =input('write a sentence --> ')

listed = sentence.split(sep=' ')
counter=0
longest = 0
myword = ''
while counter<len(listed):
    if len(listed[counter])>longest:
       longest = len(listed[counter])
       myword = listed[counter]
    counter += 1
print(myword)

sentence = input("Give me a sentence. : ")

word_list = sentence.split()

longest = 0
i = 0

while i < len(word_list) :
    
    if len(word_list[i]) > longest :
        longest = len(word_list[i])
        
    i += 1
    
print("The length of the longest word : ", longest)

names = ['Ahmed', 'Aisha', 'Adam', 'Joseph', 'Gabriel']
for n in names:
    print(f'Hello {n}')

names = ['ali', 'veli', 'hasan']
names.extend('deli')

numbers = [4, 6, 9, 11]
numbers.extend('7')

print(names)
print(numbers)

word = input('Enter a aword--> ')

for n in word:
    if n == word[len(word)-1]:
        print(n)
    else:
      print(n, end='-')

word = input('Enter a word--> ')

for n in word:
    temp = ''
    if n == word[len(word)-1]:
        temp += n
        
    else:
      temp = n + '-'
    print(temp, end = '')
    temp = ''

def convertword(digit):
      num = {0:'Zero',1:'One',2:'Two',3:'Three',4:'Four',5:'Five',6:'Six', 
             7:'Seven',8:'Eight',9:'Nine', 10:'Ten', 11:'Eleven',12:'Ten', 
             13:'Eleven', 14:'Fourteen', 15: 'Fifteen', 16: 'Sixteen',
             17: 'Seventeen', 18:'Eighteen', 19:'Nineteen', 20:'Twenty',
             30:'Thirty', 40:'Fourty',50:'Fifty', 60:'Sixty',70:'Seventy',
             80:'Eighty', 90: 'Ninety'}
      return num[digit]    

def digit2(value):
    result = ''
    if value>0 and value<20:
        result += convertword(value)
    elif value>19 and value<100:
        division = 10 * (value // 10)
        result += convertword(division)
        remind = value % 10
        if remind != 0:
            result += convertword(remind)
        
    return result
def digit3(value):
    result = ''
    if value>99 and value<1000:
         division = value // 100
         result += convertword(division) + 'Hundred'
         remind = value % 100
         if remind != 0:
            result += digit2(remind)
    return result 
def digit4(value):
    result = ''
    if value>999 and value<1000000:
         division = value // 1000
         if division<100:
            result += digit2(division) + 'Thousand'
         else:
            result += digit3(division) + 'Thousand'
         remind = value % 1000
         if remind != 0:
            result += digit3(remind)
    return result 

state =True
while state:
      number_str = input('Enter a number --> ')
      if not number_str.isdigit() or len(number_str)>6:
          print('Invalid number try again')
          state = True
      else:
        state = False
      print()

number = int(number_str)
if number<20:
    text = convertword(number)
elif number>19 and number<100:
    text = digit2(number)
elif number>99 and number<1000:
    text = digit3(number)
elif number>999 and number<1000000:
    text = digit4(number)
print(text)